MERGE INTO TAXI.DIM_VENDOR t
USING (
  SELECT 1 AS VENDOR_ID, 'Creative Mobile Technologies, LLC' AS VENDOR_NAME, TRUE AS IS_ACTIVE
  UNION ALL SELECT 2, 'VeriFone Inc.', TRUE
  UNION ALL SELECT 6, 'Myle Technologies Inc.', TRUE
  UNION ALL SELECT 7, 'Helix', TRUE
) s
ON t.VENDOR_ID = s.VENDOR_ID
WHEN MATCHED AND (t.VENDOR_NAME IS DISTINCT FROM s.VENDOR_NAME OR t.IS_ACTIVE IS DISTINCT FROM s.IS_ACTIVE) THEN
  UPDATE SET
    VENDOR_NAME = s.VENDOR_NAME,
    IS_ACTIVE = s.IS_ACTIVE,
    LAST_UPDATE_TIMESTAMP = SYSDATE()
WHEN NOT MATCHED THEN
  INSERT (VENDOR_ID, VENDOR_NAME, IS_ACTIVE)
  VALUES (s.VENDOR_ID, s.VENDOR_NAME, s.IS_ACTIVE);



MERGE INTO TAXI.DIM_RATE_CODE t
USING (
  SELECT 1 AS RATE_CODE_ID, 'Standard rate' AS RATE_CODE_DESC, TRUE AS IS_ACTIVE
  UNION ALL SELECT 2, 'JFK' , TRUE
  UNION ALL SELECT 3, 'Newark', TRUE
  UNION ALL SELECT 4, 'Nassau or Westchester', TRUE
  UNION ALL SELECT 5, 'Negotiated fare', TRUE
  UNION ALL SELECT 6, 'Group ride', TRUE
  UNION ALL SELECT 99, 'Unknown', TRUE
) s
ON t.RATE_CODE_ID = s.RATE_CODE_ID
WHEN MATCHED AND (t.RATE_CODE_DESC IS DISTINCT FROM s.RATE_CODE_DESC OR t.IS_ACTIVE IS DISTINCT FROM s.IS_ACTIVE) THEN
  UPDATE SET
    RATE_CODE_DESC = s.RATE_CODE_DESC,
    IS_ACTIVE = s.IS_ACTIVE,
    LAST_UPDATE_TIMESTAMP = SYSDATE()
WHEN NOT MATCHED THEN
  INSERT (RATE_CODE_ID, RATE_CODE_DESC, IS_ACTIVE)
  VALUES (s.RATE_CODE_ID, s.RATE_CODE_DESC, s.IS_ACTIVE);



MERGE INTO TAXI.DIM_PAYMENT_TYPE t
USING (
  SELECT 0 AS PAYMENT_TYPE, 'Flex Fare trip' AS PAYMENT_TYPE_DESC, TRUE AS IS_ACTIVE
  UNION ALL SELECT 1, 'Credit card', TRUE
  UNION ALL SELECT 2, 'Cash', TRUE
  UNION ALL SELECT 3, 'No charge', TRUE
  UNION ALL SELECT 4, 'Dispute', TRUE
  UNION ALL SELECT 5, 'Unknown', TRUE
  UNION ALL SELECT 6, 'Voided trip', TRUE
) s
ON t.PAYMENT_TYPE = s.PAYMENT_TYPE
WHEN MATCHED AND (t.PAYMENT_TYPE_DESC IS DISTINCT FROM s.PAYMENT_TYPE_DESC OR t.IS_ACTIVE IS DISTINCT FROM s.IS_ACTIVE) THEN
  UPDATE SET
    PAYMENT_TYPE_DESC = s.PAYMENT_TYPE_DESC,
    IS_ACTIVE = s.IS_ACTIVE,
    LAST_UPDATE_TIMESTAMP = SYSDATE()
WHEN NOT MATCHED THEN
  INSERT (PAYMENT_TYPE, PAYMENT_TYPE_DESC, IS_ACTIVE)
  VALUES (s.PAYMENT_TYPE, s.PAYMENT_TYPE_DESC, s.IS_ACTIVE);
