-- Create Travel Clean Task
CREATE OR REPLACE TASK DEV_DB.TAXI.SP_BUILD_TRAVEL_CLEAN_TASK
    WAREHOUSE = DEV_WH
    SCHEDULE = '5 minute'
AS
    CALL DEV_DB.TAXI.SP_BUILD_TRAVEL_CLEAN(1000)
;

ALTER TASK DEV_DB.TAXI.SP_BUILD_TRAVEL_CLEAN_TASK SUSPEND;
