-- Create Travel Clean Task
CREATE OR REPLACE TASK SP_BUILD_TRAVEL_CLEAN_TASK
    WAREHOUSE = DEV_WH
    SCHEDULE = '5 minute'
AS
    CALL SP_BUILD_TRAVEL_CLEAN(1000)
;

ALTER TASK SP_BUILD_TRAVEL_CLEAN_TASK SUSPEND;
