CREATE OR REPLACE VIEW VW_TRAVEL_CLEAN_ENRICHED AS (
    SELECT
      c.SOURCE_RAW_ID,
      c.RAW_ID,

      c.VENDOR_ID,
      v.VENDOR_NAME,

      c.PICKUP_DATETIME,
      c.DROPOFF_DATETIME,
      c.TRAVEL_DATE,

      c.PASSENGER_COUNT,
      c.TRIP_DISTANCE,

      c.RATE_CODE_ID,
      rc.RATE_CODE_DESC,

      c.STORE_AND_FWD_FLAG,

      c.PU_LOCATION_ID,
      c.DO_LOCATION_ID,

      c.PAYMENT_TYPE,
      pt.PAYMENT_TYPE_DESC,

      c.FARE_AMOUNT,
      c.EXTRA,
      c.MTA_TAX,
      c.TIP_AMOUNT,
      c.TOLLS_AMOUNT,
      c.IMPROVEMENT_SURCHARGE,
      c.TOTAL_AMOUNT,
      c.CONGESTION_SURCHARGE,
      c.AIRPORT_FEE,
      c.CBD_CONGESTION_FEE,

      c.DATA_EXCEPTIONS,
      c.CREATE_TIMESTAMP,
      c.LAST_UPDATE_TIMESTAMP

    FROM TRAVEL_CLEAN c
    LEFT JOIN DIM_VENDOR v
      ON v.VENDOR_ID = c.VENDOR_ID
     AND v.IS_ACTIVE = TRUE
    LEFT JOIN DIM_RATE_CODE rc
      ON rc.RATE_CODE_ID = c.RATE_CODE_ID
     AND rc.IS_ACTIVE = TRUE
    LEFT JOIN DIM_PAYMENT_TYPE pt
      ON pt.PAYMENT_TYPE = c.PAYMENT_TYPE
     AND pt.IS_ACTIVE = TRUE
);
